Problem Statment:
write a function so that the columns of the output matrix are power of the input vector
the order of powers is determine by the increasing boolean argument. so ecifically when increasing is false,
the i th output column is the input vector raised element wise to the power of N-i-1
HINT- such a matrix with geomatric progression in each row is named for AL exandre-Theophile vandermonde.

In [1]:
import numpy as np

In [2]:
x= np.array([1,2,3,4,5])
N = 5
matrix = np.vander(x,N,increasing=False)
print(matrix)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


OR

In [5]:
#creating matrix with output columns based on input vector
import numpy as np
x= np.array([1,2,3,4,5])
N = 5
matrix = np.column_stack([x**(N-i-1) for i in range(N)])
print(matrix)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
